apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: go-ko
spec:
  params:
  - name: gitURL
    description: the git URL to build
  - name: gitRevision
    description: the git revision to build
  - name: package
    description: package to release
  tasks:
  - name: clone
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: sources
    params:
    - name: url
      value: $(params.gitURL)
    - name: revision
      value: $(params.gitRevision)
  - name: ko-build
    runAfter: [ clone ]
    taskRef:
      name: go-ko-image
    params:
    - name: package
      value: $(params.package)
    - name: packages
      value: ./...
    workspaces:
    - name: sources
      workspace: sources
  workspaces:
  - name: sources
  results:
    - name: commit-sha
      description: the sha of the commit that was released
      value: $(tasks.clone.results.commit)

